output_dir: ~/scratch/output/diffpack

train_set:
  class: BC40Train
  path: ~/projects/rrg-bengioy-ad/graph/dataset/bc40_train
  atom_feature: residue_symbol
  bond_feature: null
  residue_feature: null
  mol_feature: null
  sanitize: true
  removeHs: true
  transform:
    class: Compose
    transforms: 
      - class: TruncateProtein
        max_length: 200
        random: True
    
valid_set:
  class: BC40Valid
  path: ~/projects/rrg-bengioy-ad/graph/dataset/bc40_valid
  atom_feature: residue_symbol
  bond_feature: null
  residue_feature: null
  mol_feature: null
  sanitize: true
  removeHs: true
  transform:
    class: Compose
    transforms: 
      - class: TruncateProtein
        max_length: 200
        random: True


task:
  class: TorsionalDiffusion
  train_chi_id: 0
  schedule_1pi_periodic:
    class: SO2VESchedule
    pi_periodic: true
    annealed_temp: 3
    cache_folder:  ~/scratch/output/diffpack
    mode: ode
  schedule_2pi_periodic:
    class: SO2VESchedule
    pi_periodic: false
    annealed_temp: 3
    cache_folder:  ~/scratch/output/diffpack
    mode: ode
  sigma_embedding:
    class: SigmaEmbeddingLayer
    input_dim: 39
    hidden_dims: [ 64, 128 ]
    sigma_dim: 64
  model:
    class: GearNet
    input_dim: 128
    hidden_dims: [128, 128, 128, 128, 128, 128]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 6
    edge_input_dim: 58
    num_angle_bin: 8
  torsion_mlp_hidden_dims: [ 64, 128 ]
  graph_construction_model:
    class: GraphConstruction
    edge_layers:
      - class: BondEdge
      - class: SpatialEdge
        radius: 4.5
        min_distance: 2
      - class: KNNEdge
        k: 10
        min_distance: 0
    edge_feature: gearnet

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0] #, 1, 2, 3]
  batch_size: 32
  log_interval: 1000

# model_checkpoint: ~/projects/rrg-bengioy-ad/graph/model_ckpt/gearnet_edge_confidence_converted.pth

train:
  num_epoch: 400
